### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jedie** [ikamensh/flynt#119]
```
$ poetry run flynt --version
0.75
$ poetry run flynt --fail-on-change --line-length=119 huey_monitor huey_monitor_tests
Traceback (most recent call last):
  File "/home/jens/.cache/pypoetry/virtualenvs/django-huey-monitor-9klx3tOT-py3.8/bin/flynt", line 8, in <module>
    sys.exit(main())
  File "/home/jens/.cache/pypoetry/virtualenvs/django-huey-monitor-9klx3tOT-py3.8/lib/python3.8/site-packages/flynt/cli.py", line 14, in main
    return sys.exit(run_flynt_cli())
  File "/home/jens/.cache/pypoetry/virtualenvs/django-huey-monitor-9klx3tOT-py3.8/lib/python3.8/site-packages/flynt/cli.py", line 128, in run_flynt_cli
    cfg = parse_pyproject_toml(toml_file)
  File "/home/jens/.cache/pypoetry/virtualenvs/django-huey-monitor-9klx3tOT-py3.8/lib/python3.8/site-packages/flynt/pyproject_finder.py", line 80, in parse_pyproject_toml
    pyproject_toml = tomli.load(f)
  File "/home/jens/.cache/pypoetry/virtualenvs/django-huey-monitor-9klx3tOT-py3.8/lib/python3.8/site-packages/tomli/_parser.py", line 55, in load
    s = __fp.read().decode()
AttributeError: 'str' object has no attribute 'decode'
```

I Tested different versions: 0.72-0.75 raised `AttributeError: 'str' object has no attribute 'decode'`
0.71 raised `ModuleNotFoundError: No module named 'black'`
And 0.70 is the last working version here.

-----

Whoops i see a v0.75 doesn't exists on github?!?
![grafik](https://user-images.githubusercontent.com/71315/148550024-1ec944fe-524e-40fc-8802-c40b5a832475.png)

But on PyPi:
![grafik](https://user-images.githubusercontent.com/71315/148550080-fa76461c-d96e-4e11-a825-177bc0794601.png)

**Comment by ikamensh** [comment]
I can't reproduce the issue. I have both integration tested using .toml config (user / project level), and can make following toy example work:

```python
import os.path
import tomli


path_config = os.path.expanduser("~/.config/clustertools.toml")

print(tomli.__version__)  # 1.1.0 works, 1.2.1 works

with open(path_config, encoding="utf8") as f:
    pyproject_toml = tomli.load(f)
    print(pyproject_toml)
```

Can it be specific to the content of toml file? Version of some dependency / library in your environment?

**Comment by ikamensh** [comment]
Re: tags, I've added 0.75 - no point in adding 0.74 now probably.

**Comment by ikamensh** [comment]
Ok clarified on the PR - the reason was using tomli 2.0, with change in #120 both tomli 1.1+ and 2.0 are supported.
