### ISSUE TITLE
forbid 3.6 install / fail gracefully

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/flynt#17]
38f9d3a65222:flynt ikkamens$ pyenv local 3.6.8
38f9d3a65222:flynt ikkamens$ pip install flynt
Collecting flynt
  Downloading https://files.pythonhosted.org/packages/4c/9f/ec11ff0b1f118674e1759a7a7e18c452cd3e58956a194ea8b262d4de7380/flynt-0.20-py3-none-any.whl
Collecting forbiddenfruit (from flynt)
  Using cached https://files.pythonhosted.org/packages/03/24/903765ffae7e2022f61dcf4fb6e972c48f9abf64cfa9eb074b6a2a7c78f3/forbiddenfruit-0.1.3.tar.gz
Collecting colorama (from flynt)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting astor (from flynt)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting pyupgrade (from flynt)
  Using cached https://files.pythonhosted.org/packages/61/4e/b64dedcccd51f66ab3e065d2cc07fc1a5491a5ecf72a48c1c8019c5cc617/pyupgrade-1.21.0-py2.py3-none-any.whl
Collecting tokenize-rt>=3.2.0 (from pyupgrade->flynt)
  Using cached https://files.pythonhosted.org/packages/a9/50/1983329a9b82496326627bfb44d2f2604913311fe6d9aa426aa4261351ea/tokenize_rt-3.2.0-py2.py3-none-any.whl
Installing collected packages: forbiddenfruit, colorama, astor, tokenize-rt, pyupgrade, flynt
  Running setup.py install for forbiddenfruit ... done
Successfully installed astor-0.8.0 colorama-0.4.1 flynt-0.20 forbiddenfruit-0.1.3 pyupgrade-1.21.0 tokenize-rt-3.2.0
You are using pip version 18.1, however version 19.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
38f9d3a65222:flynt ikkamens$ flynt .
Traceback (most recent call last):
  File "/Users/ikkamens/.pyenv/versions/3.6.8/bin/flynt", line 7, in <module>
    from flynt import main
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/flynt/__init__.py", line 10, in <module>
    from flynt.api import fstringify
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/flynt/api.py", line 12, in <module>
    from flynt.process import fstringify_code_by_line
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/flynt/process.py", line 3, in <module>
    from flynt import lexer
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/flynt/lexer/__init__.py", line 6, in <module>
    set_multiline()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/flynt/lexer/Chunk.py", line 18, in set_multiline
    Chunk.skip_tokens = (token.NEWLINE, token.NL)
AttributeError: module 'token' has no attribute 'NL'

**Comment by ikamensh** [comment]
Added 3.6 support
