### ISSUE TITLE
Does not detect directories properly?

### ISSUE THREAD

**Issue by slhck** [ikamensh/flynt#63]
Trying to run `flynt v0.46` with Python 3.8.1 under macOS:

```
~/Desktop 
➜ mkdir test

~/Desktop 
➜ echo 'print("{}".format("foo"))' > test/test.py

~/Desktop 
➜ flynt test 
Running flynt v.0.46
Traceback (most recent call last):
  File "/Users/werner/.pyenv/versions/3.8.1/bin/flynt", line 8, in <module>
    sys.exit(main())
  File "/Users/werner/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flynt/cli.py", line 80, in main
    return fstringify(
  File "/Users/werner/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flynt/api.py", line 172, in fstringify
    status = fstringify_files(
  File "/Users/werner/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flynt/api.py", line 88, in fstringify_files
    changed, count_expressions, charcount_original, charcount_new = _fstringify_file(
  File "/Users/werner/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flynt/api.py", line 25, in _fstringify_file
    with open(filename, encoding="utf-8") as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/werner/Desktop/test'
```

Just for reference:

```
~/Desktop 
➜ tree .
└─ test
   └── test.py
```

**Comment by ikamensh** [comment]
good catch, fixed in 0.46.1
