### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by asottile** [ikamensh/flynt#7]
```console
$ pip install -e .
Obtaining file:///tmp/flynt
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: ['', '/tmp/flynt/venv/lib/python36.zip', '/tmp/flynt/venv/lib/python3.6', '/tmp/flynt/venv/lib/python3.6/lib-dynload', '/usr/lib/python3.6', '/tmp/flynt/venv/lib/python3.6/site-packages']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/flynt/setup.py", line 5, in <module>
        import flynt
      File "/tmp/flynt/src/flynt/__init__.py", line 6, in <module>
        from flynt.api import fstringify_dir, fstringify_file, fstringify
      File "/tmp/flynt/src/flynt/api.py", line 7, in <module>
        import astor
    ModuleNotFoundError: No module named 'astor'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/flynt/
```

~generally you shouldn't import your package in setup.py since its dependencies are not yet installed

**Comment by ikamensh** [comment]
fixed by reading version using regular expression at install time. https://github.com/ikamensh/flynt/commit/05f4baa1899bc49db983626f9043776163fcc30a
