### ISSUE TITLE
Handle nested formatting

### ISSUE THREAD

**Issue by jendrikseipp** [ikamensh/flynt#70]
The code 

```
value = 1.2345
digits = 3
print("{value:.{digits}f}".format(value=value, digits=digits))
```

yields the exception

```
Running flynt v.0.48.1
Exception A variable was never used - a risk of bug. during conversion of code '"{value:.{digits}f}" . format ( value = value , digits = digits )'
Traceback (most recent call last):
  File "/mydir/src/flynt/transform/transform.py", line 29, in transform_chunk
    converted, changed, str_in_str = fstringify_node(copy.deepcopy(tree))
  File "/mydir/src/flynt/transform/FstringifyTransformer.py", line 91, in fstringify_node
    result = ft.visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/mydir/src/flynt/transform/FstringifyTransformer.py", line 30, in visit_Call
    result_node = joined_string(node)
  File "/mydir/src/flynt/transform/format_call_transforms.py", line 102, in joined_string
    raise FlyntException("A variable was never used - a risk of bug.")
flynt.exceptions.FlyntException: A variable was never used - a risk of bug.
fstringifying /mydir/mytest.py...no change
```

but ideally, flynt would produce 

    print(f"{value:.{digits}f}")

I think nested formatting is probably quite rare, so it may be easiest to simply log that this kind of feature is not supported and let users make the modification themselves.

**Comment by ikamensh** [comment]
Complexity of edge cases around formatting is sometimes not worth the complications of flynt code it brings from my point of view. Happy to process PR if this is sufficiently important!

Good starting point is `format_call_transforms.py -> joined_string`

**Comment by jendrikseipp** [comment]
I agree that it's probably not worth the effort to automatically transform the code.
