### ISSUE TITLE
Won't add to .pre-commit-config.yaml

### ISSUE THREAD

**Issue by tordbb** [ikamensh/flynt#79]
I am able to pip install flynt in the VS Code terminal, and running `flynt .` in the same terminal results in the successful transformation of 26 old formattings in 4 files into f-strings. Thank you!

However, when I add the section for flynt to the following .pre-commit-config.yaml, then running `pre-commit run --all-files` fails. If I remove the section about flynt, then running `pre-commit run --all-files` succeeds. 

```
# NOTE: The versions can be updated by calling
#        pre-commit autoupdate
repos:
  - repo: https://github.com/ikamensh/flynt/
    rev: ''
    hooks:
      - id: flynt

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
```

Output from .cache/pre-commit/pre-commit.log:
```
### version information

pre-commit version: 2.7.1
sys.version:
    3.7.9 (default, Aug 31 2020, 12:42:55) 
    [GCC 7.3.0]
sys.executable: /home/vagrant/miniconda/envs/hap/bin/python
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
    

Traceback (most recent call last):
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 183, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 165, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: unknown value for config 'protocol.version': 2
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/error_handler.py", line 63, in error_handler
    yield
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/main.py", line 390, in main
    return run(args.config, store, args)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/commands/run.py", line 377, in run
    for hook in all_hooks(config, store)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/repository.py", line 212, in all_hooks
    for repo in root_config['repos']
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/repository.py", line 213, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/repository.py", line 188, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/repository.py", line 154, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 187, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 144, in _new_repo
    make_strategy(directory)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 185, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 158, in _complete_clone
    git_cmd('checkout', ref)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/vagrant/miniconda/envs/hap/lib/python3.7/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'checkout', '')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```

**Comment by ikamensh** [comment]
I'm not a pre-commit  user myself, and pre-commit support was contributed to the library by the community. From what I understand, some projects use it successfully to ensure all new formatting uses f-strings. Maybe an example could help you: https://github.com/yt-project/yt/blob/master/.pre-commit-config.yaml

Furthermore, error is not raised in the flynt code so maybe searching for pre-commit specific configuration problems can help you?

**Comment by ikamensh** [comment]
closing as inactive.
