### ISSUE TITLE
ImportError when running entrypoint

### ISSUE THREAD

**Issue by asottile** [ikamensh/flynt#8]
```console
$ flynt t.py
Traceback (most recent call last):
  File "/tmp/flynt/venv/bin/flynt", line 11, in <module>
    load_entry_point('flynt', 'console_scripts', 'flynt')()
  File "/tmp/flynt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/flynt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/tmp/flynt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/tmp/flynt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'flynt'
```

from a quick look, you're missing `package_dir` in `setup.py` (for the `src` layout)

**Comment by asottile** [comment]
Here's a patch which fixes this:

```diff
diff --git a/setup.py b/setup.py
index 73a97b0..fda4b4f 100644
--- a/setup.py
+++ b/setup.py
@@ -30,7 +30,7 @@ def get_requirements():
 setup(
     name="flynt",
     packages=["flynt", "flynt.transform"],
-    package_dir={'flynt': 'src/flynt', "flynt.transform": "src/flynt/transform"},
+    package_dir={'': 'src'},
     version=VERSION,
     description="CLI tool to convert a python project's %-formatted strings to f-strings.",
     author="Hackathon Team",
@@ -49,4 +49,4 @@ setup(
     install_requires=get_requirements(),
     entry_points={"console_scripts": ["flynt=flynt:main"]},
 
-)
\ No newline at end of file
+)
```

**Comment by ikamensh** [comment]
Thanks, this is much better - don't need to repeat directories in two places. Applied this change.

**Comment by ikamensh** [comment]
p.s. actually I couldn't reproduce the problem (by installing from source). But your variant seems better nonetheless.
